# Generated by Django 2.2.8 on 2022-01-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='addrees',
            new_name='address',
        ),
    ]
