# Generated by Django 2.2.8 on 2022-01-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.BooleanField(default=True),
        ),
    ]
